apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: nfs-{{ .Release.Name }}-pod
  ports:
  - port: 111
    protocol: UDP
    name: udp111
  - port: 2049
    protocol: TCP
    name: tcp2049

